name: iposprinter
description: A flutter plugin for the iposprinter java library.
version: 0.0.2
homepage: "https://pacifylabs.com"

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/logo.png
  plugin:
    platforms:
      android:
        package: com.iposprinter_plugin
        pluginClass: IPosBluetoothPlugin